crew-z/crewz

src/main/resources/static/assets/css/default.css
src/main/resources/static/assets/css/main.css
src/main/resources/templates/include/footer.html
src/main/resources/templates/include/header.html

- header에 '모든 동아리' 버튼추가
- 로그인 버튼 색 변경
- footer CSS 수정
related to #8

feat: header, footer 수정

---

src/main/java/environment/project/controller/MainController.java
src/main/java/environment/project/controller/UserController.java
src/main/java/environment/project/dto/BoardDTO.java
src/main/java/environment/project/dto/UserDTO.java
src/main/java/environment/project/mapper/BoardMapper.java
src/main/java/environment/project/mapper/UserMapper.java
src/main/java/environment/project/service/BoardService.java
src/main/java/environment/project/service/BoardServiceImpl.java
src/main/java/environment/project/service/UserService.java
src/main/java/environment/project/service/UserServiceImpl.java
src/main/resources/application.properties
src/main/resources/static/assets/css/default.css
src/main/resources/templates/include/header.html
src/main/resources/templates/main.html

- 화면 구현
- 검색 기능 추가
- 버튼 이벤트 추가
- carousel Card 구현
- BoardDTO,BoardMapper,BoardService,BoardServiceimpl 추가
- defalut CSS 수정
- UserController,UserDTO,UserMapper,UserService,UserServiceImple 수정
- mybatis SnakeToCamel 설정 추가
Resolves #8

feat: 메인페이지 작업 및 환경 설정 변경

---

src/main/resources/application.properties
src/main/resources/templates/include/footer.html

- application.properties 수정
- footer.html 수정
resolve: #13

feat: DB정보 숨김처리, footer 수정

---

src/main/java/environment/project/controller/BoardController.java
src/main/resources/static/assets/css/board.css
src/main/resources/templates/board/board.html

담당자 : 이권석
04/28까지
- 동아리 상세페이지 html 구조 잡기
- 동아리 상세페이지 css 구조 잡기
related to #10

feat: 동아리 상세페이지 html/css 구조 만들기

---

src/main/java/environment/project/controller/MainController.java
src/main/java/environment/project/mapper/BoardMapper.java
src/main/java/environment/project/service/BoardService.java
src/main/java/environment/project/service/BoardServiceImpl.java
src/main/resources/static/assets/css/default.css
src/main/resources/templates/all.html
src/main/resources/templates/include/header.html

- 전체동아리 페이지 화면
- 동아리 리스트 목록 조회
- 검색 기능 추가
- all.html 추가
- BoardMapper에 selectServiceToSearch 추가
- MainController에 mapping 추가
resolve: #18

feat: 전체동아리 페이지, 검색 기능 추가

---

src/main/java/environment/project/controller/BoardController.java
src/main/java/environment/project/controller/MainController.java
src/main/java/environment/project/service/BoardServiceImpl.java
src/main/resources/templates/main.html

feat: 메인페이지 수정

---

src/main/java/environment/project/controller/MypageController.java
src/main/java/environment/project/mapper/MypageMapper.java
src/main/java/environment/project/service/MypageService.java
src/main/java/environment/project/service/MypageServiceImpl.java
src/main/resources/templates/clubLeaderPage.html

<hr>
- 동아리 신청 현황 조회<br>
- 동아리원 신청 승인<br>
- 동아리원 신청 반려<br>
- 반려버튼 클릭시 한번 더 확인 후 신청유저 데이터 삭제

feat: 동아리장 마이페이지_동아리 신청회원 조회

---

src/main/java/environment/project/controller/MypageController.java
src/main/java/environment/project/dto/ClubDTO.java
src/main/java/environment/project/dto/ClubInfoDTO.java
src/main/java/environment/project/mapper/MypageMapper.java
src/main/java/environment/project/service/MypageService.java
src/main/java/environment/project/service/MypageServiceImpl.java
src/main/resources/templates/clubLeaderPage.html
src/main/resources/templates/mypageMain.html

세션으로 로그인된 유저가 동아리장일 경우에만 동아리장 페이지로 이동
동아리장 페이지내에서 동아리 신청 유저의 동아리 가입 승인 업데이트
resolves: #44

feat: 로그인된 유저로 동아리장 페이지 운영

---

src/main/java/environment/project/controller/MypageController.java
src/main/java/environment/project/mapper/MypageMapper.java
src/main/java/environment/project/service/MypageService.java
src/main/java/environment/project/service/MypageServiceImpl.java
src/main/resources/templates/clubLeaderPage.html
src/main/resources/templates/include/header.html
src/main/resources/templates/mypageMain.html

마이페이지에서 현재 진행중인 동아리와 심사중인 동아리 다른 형태로 출력
마이페이지 css수정

feat: 유저 마이페이지 동아리 분리

---

src/main/java/environment/project/controller/MypageController.java
src/main/java/environment/project/mapper/MypageMapper.java
src/main/java/environment/project/service/MypageService.java
src/main/java/environment/project/service/MypageServiceImpl.java
src/main/resources/templates/clubLeaderPage.html
src/main/resources/templates/mypageMain.html

유저가 활동중인 동아리 카드에서 리뷰 작성하러가기 버튼 링크 구현
resolves: #39

feat: 유저 마이페이지 리뷰작성 버튼

---

src/main/java/environment/project/controller/BoardController.java
src/main/java/environment/project/controller/BoardReplyController.java
src/main/java/environment/project/controller/ClubInfoController.java
src/main/java/environment/project/dto/BoardCreateDTO.java
src/main/java/environment/project/dto/BoardGetDTO.java
src/main/java/environment/project/dto/BoardPeriodGetDTO.java
src/main/java/environment/project/dto/BoardReplyCreateDTO.java
src/main/java/environment/project/dto/BoardReplyGetDTO.java
src/main/java/environment/project/dto/BoardReplyUpdateDTO.java
src/main/java/environment/project/dto/BoardUpdateDTO.java
src/main/java/environment/project/dto/ClubInfoCreateDTO.java
src/main/java/environment/project/mapper/BoardMapper.java
src/main/java/environment/project/mapper/BoardReplyMapper.java
src/main/java/environment/project/mapper/ClubInfoMapper.java
src/main/java/environment/project/service/BoardReplyService.java
src/main/java/environment/project/service/BoardReplyServiceImpl.java
src/main/java/environment/project/service/BoardService.java
src/main/java/environment/project/service/BoardServiceImpl.java
src/main/java/environment/project/service/ClubInfoService.java
src/main/java/environment/project/service/ClubInfoServiceImpl.java
src/main/java/environment/project/util/BoardUtil.java
src/main/java/environment/project/util/DateUtil.java
src/main/resources/templates/board.html
src/main/resources/templates/boardCreate.html
src/main/resources/templates/boardEdit.html

- 로그인 세션으로 board, boardReply CRUD 가능하게 변경
- 동아리 합류 기능 추가
- 이미 신청한 유저는 신청완료(비활성화) 기능 추가
- board_period 테이블(DB)에 비어 있을때 생기는 에러 해결
- Mapper에 Join으로 만든 쿼리 나눠서 처리 완료
- 전체적으로 리팩토링 진행

feat: 로그인 세션으로 값 변경, 동아리 합류 기능 추가

---

src/main/java/environment/project/controller/MypageController.java
src/main/java/environment/project/dto/ClubApplyDTO.java
src/main/java/environment/project/dto/ClubNameDTO.java
src/main/java/environment/project/mapper/MypageMapper.java
src/main/java/environment/project/service/MypageService.java
src/main/java/environment/project/service/MypageServiceImpl.java
src/main/resources/static/assets/css/main.css
src/main/resources/templates/clubLeaderPage.html
src/main/resources/templates/mypageMain.html

마이페이지 동아리 신설 결과 보러 페이지 이동
동아리장페이지 동아리 이름 추가
<hr>
ClubNameDto 생성
MypageMapper 수정
MypageService 수정
MypageServiceImpl 수정
MypageController 수정
mian.css 수정
resolves: #57

feat: 마이페이지 동아리장페이지

---

src/main/java/environment/project/controller/LoginController.java
src/main/java/environment/project/service/UserService.java
src/main/java/environment/project/service/UserServiceImpl.java
src/main/resources/static/assets/css/default.css
src/main/resources/templates/login.html
src/main/resources/templates/newclub.html
src/main/resources/templates/newclubResult.html
src/main/resources/templates/newclubView.html
src/main/resources/templates/signup.html
src/main/resources/templates/signupSuccess.html

- DB에 저장되어 있지 않은 id로 로그인시 오류 발생 문제 해결
<br>
Related to #6

bug: 로그인 유효성 검사 추가 구현

---

src/main/java/environment/project/controller/MypageController.java
src/main/java/environment/project/mapper/MypageMapper.java
src/main/resources/templates/mypageMain.html

동아리장 페이지 동아리원 가입 승인 & 거절 오류
MypageController 수정
MypageMapper 수정
<br>
신설동아리 리스트 아이콘 수정
mypageMain.html 수정
resolves: #61

fix: 동아리장페이지 이슈해결

---

src/main/java/environment/project/controller/BoardController.java
src/main/java/environment/project/controller/MypageController.java
src/main/java/environment/project/dto/ClubApplyDTO.java
src/main/java/environment/project/mapper/BoardReplyMapper.java
src/main/java/environment/project/mapper/ClubInfoMapper.java
src/main/java/environment/project/mapper/MypageMapper.java
src/main/resources/static/assets/css/board.css
src/main/resources/templates/board.html
src/main/resources/templates/module/commonCss.html
src/main/resources/templates/mypageMain.html

- 마이페이지 게시물 등록 및 수정 버튼 추가
- MypageMapper selectClubApproveResult 쿼리 수정(club, board 테이블 LEFT JOIN 추가)
- ClubApplyDTO private Long clubNo, private Long boardNo 추가
resolves: #62

feat: 마이페이지 게시물 등록 버튼 추가

---

src/main/resources/templates/admin.html

- 관리자 페이지 반려버튼 클릭 시 모달창 위치가 리스트 안쪽에 생기는 버그 수정
- 화면 밖으로 모달창이 보이도록 변경
resolves: #66

fix: 관리자 페이지 버그 픽스

---

src/main/java/environment/project/controller/BoardController.java
src/main/java/environment/project/mapper/BoardMapper.java
src/main/java/environment/project/mapper/BoardReplyMapper.java
src/main/java/environment/project/mapper/ClubInfoMapper.java
src/main/java/environment/project/service/BoardService.java
src/main/java/environment/project/service/BoardServiceImpl.java
src/main/resources/static/assets/css/board.css
src/main/resources/templates/board.html
src/main/resources/templates/boardCreate.html
src/main/resources/templates/boardEdit.html
src/main/resources/templates/include/header.html
src/main/resources/templates/index.html
src/main/resources/templates/module/commonCss.html
src/main/resources/templates/module/commonJs.html

- clubNo, boardNo 부분 GET -> POST로 변경
- edit, new 페이지에서 boardtitle readonly 로 변경

feat: 테스트 후 피드백 개선 진행

---

src/main/resources/templates/mypageMain.html

- 게시물 수정 파라메터 ( clubNo -> boardNo)로 수정

feat: 게시물 수정 파라메터 변경

---

src/main/java/environment/project/controller/BoardController.java
src/main/java/environment/project/controller/MypageController.java
src/main/java/environment/project/mapper/BoardMapper.java
src/main/java/environment/project/service/BoardServiceImpl.java
src/main/resources/templates/board.html

- Board 생성, 수정시 clubNo, boardNo 잘받아와지는지 확인 완료

feat: board 생성, 수정시 clubNo, boardNo 받아오는지 확인

---

src/main/resources/templates/clubLeaderPage.html
src/main/resources/templates/mypageMain.html

마이페이지, 동아리장페이지 nav바 수정
resolves: #74

fix: 마이페이지 nav바 수정

---

src/main/java/environment/project/controller/BoardController.java
src/main/java/environment/project/mapper/BoardMapper.java
src/main/java/environment/project/mapper/BoardReplyMapper.java
src/main/java/environment/project/mapper/ClubInfoMapper.java
src/main/java/environment/project/service/BoardServiceImpl.java
src/main/resources/static/assets/css/board.css
src/main/resources/templates/board.html
src/main/resources/templates/boardCreate.html
src/main/resources/templates/boardEdit.html

- board.board_views 카운팅 기능 추가(view로는 나오지 X)
- mapper "*" 처리 변경(유지보수 고려)
- 주석 및 안쓰는 코드 전체적으로 수정

feat: board 카운팅 추가, mapper 쿼리 수정 및 주석 제거

---

src/main/java/environment/project/controller/MainController.java
src/main/resources/static/assets/css/default.css
src/main/resources/templates/all.html
src/main/resources/templates/main.html

- card 클릭 이벤트 변경
- 동아리 모집중, 기간만료 태그 추가

feat: 메인페이지 card, 목록 조회, 모든 동아리 기능 모집 태그 추가

---

src/main/java/environment/project/controller/MainController.java
src/main/java/environment/project/mapper/BoardMapper.java
src/main/java/environment/project/service/BoardService.java
src/main/java/environment/project/service/BoardServiceImpl.java
src/main/resources/templates/all.html
src/main/resources/templates/main.html

- 현재 모집 중 동아리, 인기 있는 동아리 쿼리 수정
- 기간 만료 태그 설정

feat: 메인페이지 리스트 쿼리 수정

---

src/main/resources/templates/mypageMain.html

feat: 마이페이지 css 수정

---

src/main/resources/static/assets/css/default.css
src/main/resources/templates/mypageMain.html

- 동아리 미승인 시에도 게시물 등록, 수정버튼이 노출되는 버그 수정

fix: 마이페이지 게시물 등록 버튼

---

src/main/java/environment/project/controller/BoardController.java
src/main/java/environment/project/dto/BoardReplyWithMetadata.java
src/main/resources/static/assets/css/board.css
src/main/resources/templates/board.html

- board상세페이지 리뷰 수정 권한 추가
- 로그인여부에 작성 권한 추가

feat: board상세페이지 리뷰 수정 권한 추가 및 로그인여부에 작성 권한 추가

---

src/main/resources/templates/admin.html
src/main/resources/templates/clubLeaderPage.html
src/main/resources/templates/mypageMain.html

하단에 고정되도록 수정했습니다.
resolved: #98

feat: 마이페이지, 관리자 페이지 footer 위치 수정

---

src/main/java/environment/project/controller/BoardController.java

feat: board상세페이지 리뷰 수정 권한 추가

---

build.gradle
src/main/java/environment/project/configuration/MvcConfiguration.java
src/main/java/environment/project/controller/ClubApplyController.java
src/main/java/environment/project/mapper/BoardMapper.java
src/main/java/environment/project/mapper/UserMapper.java
src/main/resources/templates/admin.html
src/main/resources/templates/all.html
src/main/resources/templates/board.html
src/main/resources/templates/boardCreate.html
src/main/resources/templates/boardEdit.html
src/main/resources/templates/clubLeaderPage.html
src/main/resources/templates/include/footer.html
src/main/resources/templates/include/header.html
src/main/resources/templates/index.html
src/main/resources/templates/login.html
src/main/resources/templates/main.html
src/main/resources/templates/module/common-css.html
src/main/resources/templates/module/commonCss.html
src/main/resources/templates/module/commonJs.html
src/main/resources/templates/mypageMain.html
src/main/resources/templates/newclub.html
src/main/resources/templates/newclubResult.html
src/main/resources/templates/newclubView.html
src/main/resources/templates/signup.html
src/main/resources/templates/signupSuccess.html

- templates에 replace처리 된 header,footer,css 경로 변경

refactor: 배포를 위한 header,footer,css 경로 수정

---

src/main/java/environment/project/controller/AdminController.java
src/main/java/environment/project/controller/BoardController.java
src/main/java/environment/project/controller/BoardReplyController.java
src/main/java/environment/project/controller/LoginController.java
src/main/java/environment/project/controller/MypageController.java
src/main/resources/templates/newclubView.html

- Debugging 처리를 위해 Controller에 로그 추가
resolved to: #104

debug: 로그 추가

---

src/main/java/environment/project/controller/BoardController.java
src/main/java/environment/project/dto/BoardCategoryDTO.java
src/main/java/environment/project/dto/BoardCreateDTO.java
src/main/java/environment/project/dto/BoardUpdateDTO.java
src/main/java/environment/project/dto/CategoryInfoDTO.java
src/main/java/environment/project/mapper/CategoryInfoMapper.java
src/main/java/environment/project/service/CategoryInfoService.java
src/main/java/environment/project/service/CategoryInfoServiceImpl.java
src/main/resources/templates/board.html
src/main/resources/templates/boardCreate.html
src/main/resources/templates/boardEdit.html

- 게시물 작성페이지 카테고리 기능 추가
- 카테고리 수정,삭제 기능 추가
resolved: #107

feat: 카테고리 기능 추가

---

build.gradle
src/main/java/environment/project/controller/MypageController.java
src/main/java/environment/project/mapper/MypageMapper.java
src/main/resources/templates/clubLeaderPage.html
src/main/resources/templates/module/commonJs.html
src/main/resources/templates/mypageMain.html

동아리장 페이지 전체 회원 리스트 조회. 동아리 승인시에만 nav바 노출
resolves: #84

feat: 동아리장페이지 동아리원 리스트 조회

---

src/main/java/environment/project/dto/BoardReplyGetDTO.java
src/main/java/environment/project/mapper/BoardReplyMapper.java
src/main/resources/templates/board.html

fix: board 페이지 댓글 이름으로 변경

---

src/main/resources/static/assets/css/board.css
src/main/resources/templates/boardCreate.html
src/main/resources/templates/boardEdit.html

담당자 : 이권석
기간 : 23.06.07
- 카테고리 디자인 변경
- resolved : #127

fix: 카테고리 디자인 변경

---

src/main/java/environment/project/controller/SignupController.java
src/main/resources/templates/signup.html

- 회원가입 유효성 검사
- 휴대폰번호 자동 하이픈 기능 추가
resolved: #126

feat: 회원 가입 유효성 검사, 휴대폰번호 자동 하이픈 추가

---

src/main/resources/static/assets/css/board.css
src/main/resources/templates/board.html

담당자 : 이권석
기간 : 23.06.08
- 동아리 합류 버튼 분기 나누기
- 활성화 비활성화 버튼으로 변경

fix: 동아리 합류 버튼 분기 나누기 && 활성화 비활성화 버튼으로 변경

---

src/main/resources/templates/basicpage.html

refactor: 메인화면 수정

---

src/main/java/environment/project/controller/BoardController.java

담당자 : 이권석
기간 : 23.06.13
- resolved: #139

fix: board 생성시 카테고리 null에러 해결
